### ISSUE TITLE
The type 'IServiceProvider' is defined in an assembly that is not referenced

### ISSUE THREAD

**Issue by xatabhk** [aspnet/DependencyInjection#385]
```
services.AddTransient<IFileProvider>(s => new PhysicalFileProvider(s.GetRequiredService<Microsoft.Extensions.PlatformAbstractions.IApplicationEnvironment>().ApplicationBasePath));
```

>dnx web
Error: C:\downloads\web\projects\zaxitech_core\src\tbweb\Startup.cs(105,4): .NETFramework,Version=v4.5.1 error CS0012: The type 'IServiceProvider' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.ComponentModel, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

Adding System.ComponentModel to project.json will not help.

**Comment by davidfowl** [comment]
Can you put your project on github and also say what DNX version you are using?

**Comment by xatabhk** [comment]
Here is the sample.

>dnx --version
Microsoft .NET Execution environment
 Version:      1.0.0-rc2-16595
 Type:         Clr
 Architecture: x86
 OS Name:      Windows
 OS Version:   10.0.10586
 Runtime Id:   win10-x86

>dotnet --version
.NET Command Line Tools (1.0.0-beta-001747)

Product Information:
 Version:     1.0.0-beta-001747
 Commit Sha:  58a8a10d41

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64

Steps:
>dnu restore
>dnx web
Error: 
(https://github.com/aspnet/DependencyInjection/files/173214/zaxitech_core_demo.zip)
Startup.cs(99,4): .NETFramework,Version=v4.5.1 error CS0012: The type 'IServiceProvider' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.ComponentModel, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

If 'dotnet restore' used, there will be another error:
 'An item with the same key has already been added. Key: System.IO Unspecified.'
[zaxitech_core_demo.zip](https://github.com/aspnet/DependencyInjection/files/173216/zaxitech_core_demo.zip)

**Comment by stefan505** [comment]
Same issue here

**Comment by Gillardo** [comment]
Same issue here, how do we sort this out?  Completely broke my app

**Comment by stefan505** [comment]
Thanks to the guys in JabbR:

 ```
"dnx451": {
      "frameworkAssemblies": {
        "System.ComponentModel": ""
      }
```

**Comment by Gillardo** [comment]
> "frameworkAssemblies": {
>         "System.ComponentModel": ""
>       }

I tried this, but kept adding version numbers and it never worked.  This seems to work fine now, thank you!

**Comment by xatabhk** [comment]
@stefan505 That works.

**Comment by pranavkm** [comment]
We're waiting to pick up newer CoreFX packages and I think that should solve these oddities. For the time being, @stefan505's suggestion should work.

**Comment by Eilon** [comment]
@pranavkm this should presumably all work now, right?

**Comment by pranavkm** [comment]
Yup. Please feel free to report if you're still seeing this with RC2 packages.

**Comment by xatabhk** [comment]
Still the same issue without adding the following lines:
"frameworkAssemblies": {
        "System.ComponentModel": ""
      }

**Comment by Eilon** [comment]
@xatabhk can you share more info on your project? Can you show the project.json file, which NuGet feeds you're using, etc.? Or best is if you can upload your project to GitHub.

**Comment by xatabhk** [comment]
@Eilon Here is the sample project. 
[zaxitech_core_demo.zip](https://github.com/aspnet/DependencyInjection/files/239737/zaxitech_core_demo.zip)

Only DNX has this issue. DOTNET.EXE works.
![iserviceprovider_error](https://cloud.githubusercontent.com/assets/6814395/14874554/439e536a-0d34-11e6-8691-ccdb94f3dc00.png)

**Comment by Eilon** [comment]
@xatabhk ah ok, DNX unfortunately doesn't work with the latest packages due to the switch to `netstandard`, among other things, and we are not planning to publish an update to DNX at this time. We recommend either using RC1 with DNX, or using RC2 with .NET CLI.
